//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuiSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fm
    {
        public int id { get; set; }
        public string LeiBie { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> IsValid { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
