//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuiSu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZhongFuHuiEntities : DbContext
    {
        public ZhongFuHuiEntities()
            : base("name=ZhongFuHuiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<fm> fm { get; set; }
        public virtual DbSet<job> job { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<newstype> newstype { get; set; }
        public virtual DbSet<partner> partner { get; set; }
        public virtual DbSet<tags> tags { get; set; }
    }
}
