//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TongYu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashi
    {
        public int id { get; set; }
        public string content { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public string jiancheng { get; set; }
    }
}
