//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TongYu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class demo_hacker_news
    {
        public int id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string by { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> score { get; set; }
    }
}
