//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TongYu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TongYuPortalDB : DbContext
    {
        public TongYuPortalDB()
            : base("name=TongYuPortalDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dashi> dashi { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<fm> fm { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<newstype> newstype { get; set; }
        public virtual DbSet<partner> partner { get; set; }
        public virtual DbSet<tags> tags { get; set; }
        public virtual DbSet<job> job { get; set; }
        public virtual DbSet<demo_hacker_news> demo_hacker_news { get; set; }
        public virtual DbSet<company> company { get; set; }
    }
}
