//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TongYu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int id { get; set; }
        public string title { get; set; }
        public string newscontent { get; set; }
        public Nullable<int> newstypeid { get; set; }
        public Nullable<int> yuedunub { get; set; }
        public string author { get; set; }
        public Nullable<int> isindex { get; set; }
        public string fengmiantu { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public string newsnub { get; set; }
    }
}
