//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TongYu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner
    {
        public int id { get; set; }
        public string partnername { get; set; }
        public string photourl { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
    }
}
